#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#dotfiles created by rediskazavr
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          
[font]
size = 12.0

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[terminal]
[terminal.shell]
program = "/bin/zsh"