#!/bin/bash
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#dotfiles created by rediskazavr
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# start program
picom &
polybar &
alacritty &
feh --bg-scale ~/.config/wallpapers/cookie_main.png &
# xrandr --output Virtual-1 --mode 1920x1080 --rate 60 & # if you using Virtual Machine and resolution work not correctly

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a state=floating follow=on 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"